<div style="border-bottom:1px solid #334973; color:#334973; padding-bottom:2px; text-align:justify">
<a target="_blank" href="../../docs/manuales/manual.pdf" title="Descarga de manual de usuario" style="margin-left:10px"><img border="0" name="libros" id="libros" src="<?php echo  $_SESSION['rutaimg'];?>libros.gif" />&nbsp;Descarga de manual de usuario</a>	
</div>
<br />
<p align="justify" style="margin-left:10px">A continuación puede acceder a cualquiera de las siguientes opciones de gestión:</p>
<p align="left" style="margin-left:10px; margin-right:10px"><img src="<?php echo  $_SESSION['rutaimg'];?>bullet_enlaces.gif" align="absmiddle" />&nbsp;&nbsp;<a href="../inmuebles/index.php" title="Gestión de inmuebles" style="margin-left:10px">Inmuebles</a></p>
<p align="left" style="margin-left:10px; margin-right:10px"><img src="<?php echo  $_SESSION['rutaimg'];?>bullet_enlaces.gif" align="absmiddle" />&nbsp;&nbsp;<a href="../usuarios/index.php" title="Gestión de usuarios" style="margin-left:10px">Usuarios</a></p>
<p align="left" style="margin-left:10px; margin-right:10px"><img src="<?php echo  $_SESSION['rutaimg'];?>bullet_enlaces.gif" align="absmiddle" />&nbsp;&nbsp;<a href="../clientes/index.php" title="Gestión de clientes" style="margin-left:10px">Clientes</a></p>
<p align="left" style="margin-left:10px; margin-right:10px"><img src="<?php echo  $_SESSION['rutaimg'];?>bullet_enlaces.gif" align="absmiddle" />&nbsp;&nbsp;<a href="../noticias/index.php" title="Gestión de noticias" style="margin-left:10px">Noticias</a></p>
<p align="left" style="margin-left:10px; margin-right:10px"><img src="<?php echo  $_SESSION['rutaimg'];?>bullet_enlaces.gif" align="absmiddle" />&nbsp;&nbsp;<a href="../informes/index.php" title="Gestión de informes" style="margin-left:10px">Informes</a></p>
<p align="left" style="margin-left:10px; margin-right:10px"><img src="<?php echo  $_SESSION['rutaimg'];?>bullet_enlaces.gif" align="absmiddle" />&nbsp;&nbsp;<a href="../plantillas/index.php" title="Modelos de plantillas" style="margin-left:10px">Plantillas</a></p>